# Generated by Django 3.1.5 on 2021-01-11 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210111_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='leveluser',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.leveluser'),
        ),
    ]
